export enum SocialType {
  behance = 'Behance',
  dribbble = 'Dribbble',
  facebook = 'Facebook',
  github = 'GitHub',
  instagram = 'Instagram',
  linkedin = 'LinkedIn',
  twitch = 'Twitch',
  twitter = 'Twitter',
  pinterest = 'PInterest',
  rss = 'RSS',
  stackoverflow = 'Stack Overflow',
  steam = 'Steam',
  youtube = 'YouTube',
}
